import = [
"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
dynamic_padding = true
dimensions = {columns = 130, lines = 35}
opacity = 0.86
decorations = "none"

[window.padding]
x = 7
y = 7

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]


